//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "MainPage.xaml.h"

void ::BingMap::MainPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///MainPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::BingMap::MainPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 2:
            {
                this->RootGrid = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
            }
            break;
        case 3:
            {
                this->mMap = safe_cast<::Windows::UI::Xaml::Controls::Maps::MapControl^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Maps::MapControl^>(this->mMap))->Loaded += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::BingMap::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::MapLoaded);
                (safe_cast<::Windows::UI::Xaml::Controls::Maps::MapControl^>(this->mMap))->MapTapped += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::Controls::Maps::MapControl^, ::Windows::UI::Xaml::Controls::Maps::MapInputEventArgs^>(this, (void (::BingMap::MainPage::*)
                    (::Windows::UI::Xaml::Controls::Maps::MapControl^, ::Windows::UI::Xaml::Controls::Maps::MapInputEventArgs^))&MainPage::MapClick);
            }
            break;
        case 4:
            {
                this->StatusBlock = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::BingMap::MainPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


